### ISSUE TITLE
Reproducing results in the paper

### ISSUE THREAD

**Issue by vinnamkim** [microsoft/Semi-supervised-learning#11]
Hi, Thanks for your great works!

I'm trying to reproduce CV results in your paper (Table 6). However, I found that some gaps between the paper and what I reproduced. I just ran training with the config files existed in the repository.

For CIFAR100 with 200 labels dataset, the result I got is as follows.
![image](https://user-images.githubusercontent.com/26541465/190842227-af488500-7e5c-4560-a4ef-176212d88bed.png)

|           | Paper top-1 error | Reproduced top-1 error | Difference |
| --------- | ----------------- | ---------------------- | ---------- |
| fixmatch  | 56.43             | 45.98                  | 10.45      |
| flexmatch | 29.59             | 36.34                  | \-6.75     |
| simmatch  | 35.94             | 30.39                  | 5.55       |

I know I used just one repetition without averaging on multiple seeds. But, those differences seem beyond deviation.

So, I started reading your paper more closely and I found out my `fixmatch` reproduced result is close to the number in Table D.1 (`lr=5e-5`, same with the configuration file).
![image](https://user-images.githubusercontent.com/26541465/190842473-dc89808a-42d3-49ad-ad72-21d8fb4de82d.png)

It leads me to think that Table 6 results may come from other hyperparameter settings. Would you help me to correctly reproduce the results reported in the paper? Thanks in advance! :smiley:

p.s. Table 6 has typos.
![image](https://user-images.githubusercontent.com/26541465/190842723-5cfc93be-e887-4099-bcb7-7cc639cb6be9.png)

**Comment by qianlanwyd** [comment]
Yes, we have modified the codes and hyper-parameters(For example, we will use layer-wise learning rate for better results in the new version and upload codes for SOTA imbalanced SSL algorithms).
We will upload new codes and logs/model checkpoints very soon. Besides, we will modify the results in the paper and will continuously update results if codes modified.

**Comment by vinnamkim** [comment]
@qianlanwyd 

Hi, thanks for the reply, I hope it will be soon. Besides, can I ask about a text file (` './data/semi_fgvc/semi_aves/l_train_val.txt'`) required for Semi-AVES dataset? I downloaded the dataset from https://www.kaggle.com/c/semi-inat-2020, but I could not find this file anywhere.

```
Traceback (most recent call last):
  File "train.py", line 364, in <module>
    main(args)
  File "train.py", line 73, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 118, in main_worker
    dataset_dict = get_dataset(args, args.algorithm, args.dataset, args.num_labels, args.num_classes, args.seed, args.data_dir)
  File "/local_ssd3/vinnamki/Semi-supervised-learning/semilearn/utils.py", line 117, in get_dataset
    lb_dset, ulb_dset, eval_dset = get_semi_aves(args, algorithm, dataset, train_split='l_train_val', data_dir=data_dir)
  File "/local_ssd3/vinnamki/Semi-supervised-learning/semilearn/datasets/cv_datasets/aves.py", line 47, in get_semi_aves
    train_labeled_dataset = iNatDataset(alg, data_dir, train_split, dataset, transform=transform_weak)
  File "/local_ssd3/vinnamki/Semi-supervised-learning/semilearn/datasets/cv_datasets/aves.py", line 103, in __init__
    self.samples, self.num_classes, self.targets = make_dataset(self.dataset_root,
  File "/local_ssd3/vinnamki/Semi-supervised-learning/semilearn/datasets/cv_datasets/aves.py", line 62, in make_dataset
    with open(split_file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/semi_fgvc/semi_aves/l_train_val.txt'
```

**Comment by YUE-FAN** [comment]
Hi vinnamkim,

We followed "[A Realistic Evaluation of Semi-Supervised Learning for Fine-Grained Classification](https://arxiv.org/abs/2104.00679)" for the dataset construction. The required file can be found [here](https://github.com/cvl-umass/ssl-evaluation/blob/main/data/semi_aves/l_train_val.txt).

**Comment by Hhhhhhao** [comment]
Updated in https://github.com/microsoft/Semi-supervised-learning/commit/fb36c1c1c2153e9f60826529e39826ee0d256c14
