### ISSUE TITLE
unbalanced classification

### ISSUE THREAD

**Issue by muziyi19** [microsoft/Semi-supervised-learning#32]
Hi, I got a question that when  the version include the unbalanced classification algorithms like COSSL and DASO will be released?

**Comment by Hhhhhhao** [comment]
We plan to release the imbalanced algorithms in end of Nov, or beginning of Dec. We still have some code tweak to accommodate the imbalanced algorithms and have to run the experiments to get evaluation of these algorithms too.

**Comment by muziyi19** [comment]
ok, thanks,

**Comment by niubilityad** [comment]
Hi, thank you for your great job! I also want to know whether imbalanced algorithms be released soon?

**Comment by Hhhhhhao** [comment]
> Hi, thank you for your great job! I also want to know whether imbalanced algorithms be released soon?

Expected this week.

**Comment by Hhhhhhao** [comment]
Updated in 69a2afc8ecc9ec29cbf6afb123035d2be3443568

**Comment by weiliangwuw** [comment]
Traceback (most recent call last):
  File "train.py", line 416, in <module>
    main(args)
  File "train.py", line 320, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 399, in main_worker
    model.train()
  File "/data/gauss/wlw/Semi-supervised-learning-main/semilearn/core/algorithmbase.py", line 349, in train
    self.call_hook("before_train_epoch")
  File "/data/gauss/wlw/Semi-supervised-learning-main/semilearn/core/algorithmbase.py", line 560, in call_hook
    getattr(hook, fn_name)(self, *args, **kwargs)
  File "/data/gauss/wlw/Semi-supervised-learning-main/semilearn/imb_algorithms/cossl/cossl.py", line 85, in before_train_epoch
    init_teacher, init_ema_teacher = classifier_warmup(algorithm.args, copy.deepcopy(algorithm.ema_model),
  File "/data/gauss/wlw/Semi-supervised-learning-main/semilearn/imb_algorithms/cossl/utils.py", line 82, in classifier_warmup
    tfe_model = weight_imprint(args, copy.deepcopy(model), train_labeled_set, num_class, gpu)
  File "/data/gauss/wlw/Semi-supervised-learning-main/semilearn/imb_algorithms/cossl/utils.py", line 268, in weight_imprint
    new_weight = torch.zeros(num_classes, model.module.backbone.num_features)
  File "/data/.conda/envs/usb/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CoSSL_Net' object has no attribute 'module'

当我训练到中间的时候出现了这个错误，这是怎么回事呢？已经迭代了81920次了，
我是在freematch的算法，加入了cossl,配置文件如图所示：
![image](https://github.com/microsoft/Semi-supervised-learning/assets/28140274/2256be24-6c19-4d8e-bc21-7e52f7fbb303)
